image: harbor.dtyunxi.cn/library/yunxicibase:0.3.0

stages:
  - test

bdd-test:
  when: always
  stage: test
  script:
    - echo "starting bdd test"
    - mvn clean post-integration-test -f pom.xml -U -P test-bdd
  only:
    - master
  allow_failure: true